src/Entity/News.php
<?php

namespace App\Entity;

use App\Repository\NewsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: NewsRepository::class)]
class News
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $title;

    #[ORM\Column(type: 'datetime')]
    private $date_added;

    #[ORM\Column(type: 'text')]
    private $annotation;

    #[ORM\Column(type: 'text')]
    private $news_text;

    #[ORM\Column(type: 'integer')]
    private $number_of_views;

    #[ORM\Column(type: 'string', length: 255)]
    private $photo;

    #[ORM\OneToMany(mappedBy: 'news', targetEntity: Comment::class, orphanRemoval: true)]
    private $comments;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'news')]
    #[ORM\JoinColumn(nullable: false)]
    private $User;

    public function __toString(): string
    {
        return (string) $this->getNumberOfViews();
    }

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDateAdded(): ?\DateTimeInterface
    {
        return $this->date_added;
    }

    public function setDateAdded(\DateTimeInterface $date_added): self
    {
        $this->date_added = $date_added;

        return $this;
    }

    public function getAnnotation(): ?string
    {
        return $this->annotation;
    }

    public function setAnnotation(string $annotation): self
    {
        $this->annotation = $annotation;

        return $this;
    }

    public function getNewsText(): ?string
    {
        return $this->news_text;
    }

    public function setNewsText(string $news_text): self
    {
        $this->news_text = $news_text;

        return $this;
    }

    public function getNumberOfViews(): ?int
    {
        return $this->number_of_views;
    }

    public function setNumberOfViews(int $number_of_views): self
    {
        $this->number_of_views = $number_of_views;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setNews($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getNews() === $this) {
                $comment->setNews(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }
}

src/Form/NewsType.php
<?php

namespace App\Form;

use App\Entity\News;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class NewsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title',TextType::class, [
                'label'=>'Название новости'
            ])
            ->add('annotation',TextType::class, [
                'label'=>'Аннотация'
            ])
            ->add('news_text',TextType::class, [
                'label'=>'Текст новости'
            ])
            ->add('photo',TextType::class, [
                'label'=>'Фото'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => News::class,
        ]);
    }
}

src/Controller/NewsController.php
<?php

namespace App\Controller;

use App\Entity\News;
use App\Entity\User;
use App\Entity\Comment;
use App\Form\NewsType;
use App\Repository\NewsRepository;
use App\Repository\UserRepository;
use App\Repository\CommentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/news')]
class NewsController extends AbstractController
{
    #[Route('/', name: 'app_news_index', methods: ['GET'])]
    public function index(NewsRepository $newsRepository): Response
    {
        return $this->render('news/index.html.twig', [
            'news' => $newsRepository->findAll(),
        ]);
    }



    #[Route('/new', name: 'app_news_new', methods: ['GET', 'POST'])]
    public function new(Request $request, NewsRepository $newsRepository): Response
    {
        $news = new News();
        $user = $this->getUser();
        $news->setDateAdded(new \DateTime('now'));
        $news->setUser($user);
        $news -> setNumberOfViews(0);
        $form = $this->createForm(NewsType::class, $news);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $newsRepository->add($news);
            return $this->redirectToRoute('app_news_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('news/new.html.twig', [
            'news' => $news,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_news_show', methods: ['GET'])]
    public function show(News $news, UserRepository $userRepository, CommentRepository $commentRepository): Response
    {
        return $this->render('news/show.html.twig', [
            'news' => $news,
            'comments' => $commentRepository->findAll(),
            'users' => $userRepository->findAll()
        ]);
    }

    #[Route('/{id}/edit', name: 'app_news_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, News $news, NewsRepository $newsRepository): Response
    {
        $form = $this->createForm(NewsType::class, $news);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $newsRepository->add($news);
            return $this->redirectToRoute('app_news_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('news/edit.html.twig', [
            'news' => $news,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_news_delete', methods: ['POST'])]
    public function delete(Request $request, News $news, NewsRepository $newsRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$news->getId(), $request->request->get('_token'))) {
            $newsRepository->remove($news);
        }

        return $this->redirectToRoute('app_news_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route(path: '/logout', name: 'app_logout')]
    public function logout(): void
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }
}

templates/news/_delete_form.html.twig
<form method="post" action="{{ path('app_news_delete', {'id': news.id}) }}" onsubmit="return confirm('Вы уверены, что хотите удалить этот элемент?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ news.id) }}">
    <button class="btn">Удалить</button>
</form>

templates/news/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-outline-dark">{{ button_label|default('Сохранить') }}</button>
{{ form_end(form) }}

templates/news/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit News{% endblock %}

{% block body %}
<div class="container">
    <h1>Редактировать новость</h1>

    {{ include('news/_form.html.twig', {'button_label': 'Сохранить изменения'}) }}

    <a href="{{ path('app_news_index') }}"><button type="button" class="btn btn-dark mb-3">На главную</button></a>


    {{ include('news/_delete_form.html.twig') }}
</div>
{% endblock %}

templates/news/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}News index{% endblock %}

{% block body %}
    <div class="bg-secondary bg-opacity-25 pb-5">
        <div class="container">




            <div class="row row-cols-1 row-cols-md-3 g-4 p-2" >

                {% for news in news %}

                    <div class="col">
                        <div class="card h-100 shadow">
                            <div class="card-header">
                                <a href="{{ path('app_news_show', {'id': news.id}) }}">
                                    <img src="{{ news.photo }}" class="card-img-top" alt="..." style="object-fit: cover; object-position: center;height: 20vw;">
                                </a>
                            </div>

                            <div class="card-body">
                                <a href="{{ path('app_news_show', {'id': news.id}) }}" class="text-decoration-none text-dark">
                                    <div>
                                        <h5 class="card-title">{{ news.title }}</h5>
                                        <small class="text-muted">{{ news.dateAdded ? news.dateAdded|date('Y-m-d H:m') : '' }}</small>
                                        <p class="card-text">{{ news.annotation }}</p>
                                    </div>
                                </a>
                            </div>

                            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start card-footer">

                                       <a href="{{ path('app_news_show', {'id': news.id}) }}" class="col-6 col-md-12 col-xl-6 ml-auto mb-md-1 mb-xl-0">
                                           <button type="button" class="btn btn-outline-dark">Посмотреть</button>
                                       </a>
                                {% if app.user  and app.user == news.user %}
                                       <a href="{{ path('app_news_edit', {'id': news.id}) }}" class="col-6 col-md-12 col-xl-6 mr-auto">
                                           <button type="button" class="btn btn-outline-dark">Редактировать</button>
                                       </a>
                                {% endif %}
                            </div>
                        </div>
                    </div>


                {% else %}
                    <tr>
                        <td colspan="8">no records found</td>
                    </tr>
                {% endfor %}
            </div>

        </div>
    </div>
{% endblock %}

templates/news/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New News{% endblock %}

{% block body %}
    <div class="container">
        <h1>Создать новость</h1>

        {{ include('news/_form.html.twig') }}

        <a href="{{ path('app_news_index') }}"><button type="button" class="btn btn-dark mb-3">На главную</button></a>

    </div>
{% endblock %}

templates/news/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}News{% endblock %}

{% block body %}

    <div class="bg-secondary bg-opacity-10 pb-5">
        <div class="card mb-3 text-white  bg-dark bg-gradient rounded-0 border-dark" style="width: content-box">
            <div class="container">
                <div class="card-body">
                    <div class="row g-0">
                        <div class="col-md-5" style="margin: 0 auto; padding: 0; ">
                            <div class="card-body">
                                <h1 class="card-title ">{{ news.title }}</h1>
                                <p class="card-text lh-lg">{{ news.annotation }}</p>
                                <div>
                                    <p class="card-text lh-lg" style="color: #AAAAAA">Количество просмотров: {{ news.numberOfViews }} <br>
                                        Дата добавления: {{ news.dateAdded ? news.dateAdded|date('Y-m-d ') : '' }}</p>
                                </div>
                            </div>

                        </div>

                        <div class="col-md-6" style="margin: 0 auto; padding: 0; ">
                            <img src="{{ news.photo }}"  alt="..." style="width: 100%;">
                        </div>

                    </div>
                </div>
            </div>
        </div>

        <div class="container">
            <p class="lead my-3">{{ news.newsText|nl2br }}</p>


            <a href="{{ path('app_news_index') }}"><button type="button" class="btn btn-dark mb-3">На главную</button></a>


            <div class=" row g-2 mb-3">
                <div class="col-10">
                    <textarea class="form-control" id="exampleFormControlTextarea1" rows="2"></textarea>
                </div>
                <div class="col-2">
                    <div class="modal fade" id="exampleModalToggle" aria-hidden="true" aria-labelledby="exampleModalToggleLabel" tabindex="-1">
                        <div class="modal-dialog modal-dialog-centered">
                            <div class="modal-content">
                                <div class="modal-body">
                                    <p>К сожалению отправка сообщения временно недоступна. Приносим извинения за доставленные неудобства.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <a class="btn btn-primary " data-bs-toggle="modal" href="#exampleModalToggle" role="button">Отправить</a>

                </div>
            </div>

            {% for comment in comments %}
                {% if comment.news == news %}
                    {% for user in users %}
                        {% if comment.user == user and comment.moderationstatus =='одобрено' %}
                            <div class="d-flex bg-light pt-3 shadow p-3">
                                <img src="{{ user.avatar }}" class="card-img col-2 m-1" alt="..."  style="object-fit: cover; object-position: center;height: 45px;width: 45px;">
                                <div class="col-10 mb-0 small lh-sm border-bottom" style="margin-left: 10px">
                                    <a href="{{ path('app_user_show', {'id': user.id}) }}" class="text-decoration-none text-dark fs-6"><strong class="d-block text-gray-dark">@{{ user.name }} </strong></a>
                                    <p class="mb-0"><small class="text-muted"> {{ comment.dateAdded ? news.dateAdded|date('Y-m-d H:m') : '' }}</small></p>
                                    <p class="fs-6">
                                        {{ comment.commenttext}}
                                    </p>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            {% endfor %}



        </div>
    </div>

{% endblock %}