src/Entity/News.php
<?php

namespace App\Entity;

use App\Repository\NewsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: NewsRepository::class)]
class News
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $title;

    #[ORM\Column(type: 'datetime')]
    private $date_added;

    #[ORM\Column(type: 'text')]
    private $annotation;

    #[ORM\Column(type: 'text')]
    private $news_text;

    #[ORM\Column(type: 'integer')]
    private $number_of_views;

    #[ORM\Column(type: 'string', length: 255)]
    private $photo;

    #[ORM\OneToMany(mappedBy: 'news', targetEntity: Comment::class, orphanRemoval: true)]
    private $comments;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'news')]
    #[ORM\JoinColumn(nullable: false)]
    private $User;

    public function __toString(): string
    {
        return (string) $this->getNumberOfViews();
    }

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDateAdded(): ?\DateTimeInterface
    {
        return $this->date_added;
    }

    public function setDateAdded(\DateTimeInterface $date_added): self
    {
        $this->date_added = $date_added;

        return $this;
    }

    public function getAnnotation(): ?string
    {
        return $this->annotation;
    }

    public function setAnnotation(string $annotation): self
    {
        $this->annotation = $annotation;

        return $this;
    }

    public function getNewsText(): ?string
    {
        return $this->news_text;
    }

    public function setNewsText(string $news_text): self
    {
        $this->news_text = $news_text;

        return $this;
    }

    public function getNumberOfViews(): ?int
    {
        return $this->number_of_views;
    }

    public function setNumberOfViews(int $number_of_views): self
    {
        $this->number_of_views = $number_of_views;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setNews($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getNews() === $this) {
                $comment->setNews(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html class="h-100">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}

    </head>
    <body class="d-flex flex-column h-100">
    <header class="p-3 bg-dark text-whitemb-4 ">
        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a class="navbar-brand" href="{{ path('app_news_index') }}">
                    <img src="https://dummyimage.com/300x100/212529/ffffff&text=News"  height="40" alt="" loading="lazy">
                </a>
                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">

                </ul>




                    {% if app.user %}
                        <div class="d-flex">
                            <div class="nav d-flex col-12 col-lg-auto justify-content-center mb-2 mb-lg-0">
                                <p class="text-white fs-6 m-auto me-2 text-start">
                                    Здравствуйте {{ app.user.name}}
                                </p>
                                <a href="{{ path('app_news_new') }}" class="m-auto">
                                    <button type="button" class="btn btn-warning  me-2" >Создать новость</button>
                                </a>
                            </div>

                        {% if is_granted('ROLE_ADMIN')  %}
                            <a href="/admin" class="m-auto">
                                <button type="button" class="btn btn-warning  me-2" >Административная панель</button>
                            </a>
                            {% endif %}
                        </div>
                            <div class="text-end">
                                <div class="col-auto">
                                    <a href="{{ path('app_logout') }}">
                                        <button type="button" class="btn btn-outline-light mt-auto" >Выйти</button>
                                    </a>
                                </div>
                            </div>

                    {% else %}
                        <div class="text-end">
                            <div class="d-flex">
                                <a href=" {{ path('app_login') }}">
                                    <button type="button"  class="btn btn-outline-light me-2">Войти</button>
                                </a>
                                <a href="{{ path('app_register') }}">
                                    <button type="button" class="btn btn-warning ">Зарегистрироваться</button>
                                </a>
                            </div>
                        </div>
                    {% endif %}


            </div>
        </div>
    </header>
    {% block body %}{% endblock %}


    <footer class="footer mt-auto py-3">
        <div class="container">
            <p class="text-muted text-center">© 2022 Пустовалова</p>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    </body>
</html>